apiVersion: v1
kind: Service
metadata:
  name: myredis
spec:
  type: NodePort
  ports:
  - port: 6379
  selector:
    app: myredis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myredis
spec:
  selector:
    matchLabels:
      app: myredis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myredis
    spec:
      containers:
      - image: localhost:32000/redis
        name: myredis
        env:
        - name: REDIS_ROOT_PASSWORD
          value: student
        ports:
        - containerPort: 6379
          name: myredis
